# Generated by Django 2.2.3 on 2019-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20190710_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family',
        ),
        migrations.AddField(
            model_name='language',
            name='family',
            field=models.ManyToManyField(to='languages.Family'),
        ),
    ]
