# Generated by Django 2.2.3 on 2019-07-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='languages',
        ),
        migrations.AddField(
            model_name='language',
            name='countries',
            field=models.ManyToManyField(to='languages.Countries'),
        ),
    ]
